language: php

sudo: false

git:
    depth: 1

env:
    global:
        - MIN_PHP=5.5.9
        - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/versions/5.6/bin/php

services:
    - mysql

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low
    fast_finish: true

before_install:
  - mysql -e "create database IF NOT EXISTS symfony;" -uroot

install:
    - composer update --prefer-dist
