<?php

namespace AppBundle\Controller;

/**
 * Generated by Symfonian Indonesia Admin Bundle
 * Url: https://github.com/symfonyid/adminbundle
 */

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfonian\Indonesia\AdminBundle\Annotation\Crud;
use Symfonian\Indonesia\AdminBundle\Annotation\Page;
use Symfonian\Indonesia\AdminBundle\Annotation\Plugins;
use Symfonian\Indonesia\AdminBundle\Controller\CrudController;

/**
 * @Route("/idname")
 *
 * @Page("IdName", description="Description of IdName")
 * @Crud("AppBundle\Entity\IdName", form="AppBundle\Form\IdNameType", menuIcon="fa-bars")
 * @Plugins(bulkInsert=true)
 */
class IdNameController extends CrudController
{
    public function getClassName()
    {
        return __CLASS__;
    }
}