app:
  resource: '@AppBundle/Controller/'
  type: annotation

admin:
    resource: '@AppBundle/Admin/'
    type: siab
    prefix: /admin

_symfonian_indonesia:
    resource: '@SymfonianIndonesiaAdminBundle/Resources/config/routing.yml'
    prefix: /admin